### ISSUE TITLE
Set up GitHub Pages

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/documentation#2]
Will need to set up Jekyll locally or let Travis CI handle it.

**Comment by jvanulde** [comment]
ECCC has a nice set of pages describing their data and services:

https://eccc-msc.github.io/open-data/readme_en/

**Comment by anthonyfok** [comment]
aHHHhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by anthonyfok** [comment]
## TODO (as of 2021-03-02):

- [x] Get GitHub Actions to work properly: AsciiDoc files got skipped somehow?
- [x] When autogeneration from AsciiDoc is working, push `gh-pages-source` from my personal repo (https://github.com/anthonyfok/documentation), check and make sure `gh-pages branch is automatically created, and ask Joost to enable GitHub Pages for this repo.
3. Maybe close this issue?
4. Open a new issue on this repo, referring to https://github.com/OpenDRR/opendrr-platform/issues/118
5. Address other potential issues, e.g.:
    * Accessibility (test with screen reader, for instance)
    * gcweb-jekyll: Update our copy to v1.1.0, and eventually migrate to `master` (or v2?) with new API?  See https://github.com/wet-boew/gcweb-jekyll and https://github.com/wet-boew/gcweb-jekyll/issues/21
    * Hugo?  Gatsby?  (Haha!)
    * etc.

**Comment by anthonyfok** [comment]
An initial documentation website demonstrated during Iteration Review back on Thu 2021-02-25 for [Sprint 28](https://github.com/OpenDRR/opendrr-platform/wiki/Sprint-28), so I am closing this issue...

... and leaving future improvement in Issue #11.  :wink:
